//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.people = new HashSet<person>();
        }
    
        public int AddressId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Zip5 { get; set; }
        public string Zip4 { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<person> people { get; set; }
        public virtual state state { get; set; }
    }
}
