//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int AttendanceId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> MinistryEventId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ministryevent ministryevent { get; set; }
        public virtual person person { get; set; }
    }
}
