//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class biblestudyevent
    {
        public int BibleStudyEventId { get; set; }
        public int TeacherId { get; set; }
        public int StudentId { get; set; }
        public int BibleStudyId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual biblestudy biblestudy { get; set; }
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
    }
}
