//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurchEntities : DbContext
    {
        public ChurchEntities()
            : base("name=ChurchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<agegroup> agegroups { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<biblestudy> biblestudies { get; set; }
        public virtual DbSet<biblestudyevent> biblestudyevents { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<interest> interests { get; set; }
        public virtual DbSet<maritalstatu> maritalstatus { get; set; }
        public virtual DbSet<ministry> ministries { get; set; }
        public virtual DbSet<ministryevent> ministryevents { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<visitorinterest> visitorinterests { get; set; }
        public virtual DbSet<visitorinterview> visitorinterviews { get; set; }
    }
}
