//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class maritalstatu
    {
        public maritalstatu()
        {
            this.visitorinterviews = new HashSet<visitorinterview>();
            this.people = new HashSet<person>();
        }
    
        public int MaritalStatusId { get; set; }
        public string MaritalStatusCode { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<visitorinterview> visitorinterviews { get; set; }
        public virtual ICollection<person> people { get; set; }
    }
}
