//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.cities = new HashSet<city>();
            this.addresses = new HashSet<address>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<city> cities { get; set; }
        public virtual ICollection<address> addresses { get; set; }
    }
}
