//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitorinterview
    {
        public int VisitorInterviewId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<bool> InterestedInBibleStudy { get; set; }
        public Nullable<System.DateTime> VisitationDate { get; set; }
        public string StreetAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> PreferredMethodOfContact_Phone { get; set; }
        public Nullable<bool> PreferredMethodOfContact_Mail { get; set; }
        public Nullable<bool> PreferredMethodOfContact_Email { get; set; }
        public Nullable<System.TimeSpan> BestTimeToCall { get; set; }
        public Nullable<bool> FirstTimeGuest { get; set; }
        public Nullable<bool> SecondTimeGuest { get; set; }
        public Nullable<bool> ThirdTimeGuest { get; set; }
        public Nullable<int> AgeGroupId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> VisitorInterestsId { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual agegroup agegroup { get; set; }
        public virtual city city { get; set; }
        public virtual maritalstatu maritalstatu { get; set; }
        public virtual person person { get; set; }
    }
}
